version: "3.7"

services:
  frontend:
    build: frontend
    volumes:
      # Mount source-code for development
      - ./:/app

  backend:
    build: backend
    volumes:
      # Mount source-code for development
      - ./:/app

  console:
    build: console
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    working_dir: /app

  storage:
    build: storage
    volumes:
      # Mount source-code for development
      - ./:/app

  api:
    build: api
    volumes:
      # Mount source-code for development
      - ./:/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./docker/nginx/dev/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - api
      - frontend
      - backend
      - console
      - storage

  node:
    image: node:16-alpine
    volumes:
      - ./:/app
    working_dir: /app

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080

  db:
    image: mysql:8
    volumes:
      - db:/var/lib/mysql/
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees_board
      MYSQL_USER: employees_board_user
      MYSQL_PASSWORD: employees_board_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: mariadb
    volumes:
      - phpmyadmin_data:/var/www/html/

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always

networks:
  default:
    name: employees_board_default

volumes:
  db:
  phpmyadmin_data: